"""change kickoff emails from string to a json datatype'


Revision ID: 82fdcc856093
Revises: 2caf868916e8
Create Date: 2023-09-15 08:50:42.317928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82fdcc856093'
down_revision = '2caf868916e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kickofflabs_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emails', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kickofflabs_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('emails')

    # ### end Alembic commands ###
